### ISSUE TITLE
Fit images in note by Width

### ISSUE THREAD

**Issue by helluvamatt** [helluvamatt/dotnet-smallnotes#7]
Images should resize to fit in the note:

``` css
img
{
    max-width: 100%;
}
```

Render images as clickable links that will open the picture in the browser:

``` html
<a href="file:///path/to/image.jpg">
    <img src="file:///path/to/image.jpg">
</a>
```
